import FoodCard from "../components/cards/FoodCard";
import InputSearch from "../components/search/InputSearch";
import CartItems from "./cart/CartItems";
import style from "./foods.module.css";

const getFoods = async (search) => {
  const res = await fetch(
    `https://taxi-kitchen-api.vercel.app/api/v1/foods/random?search=${search}`,
    { next: { revalidate: 10 } }
  );
  const data = await res.json();
  await new Promise((resolve) => setTimeout(resolve, 3000));
  return data.foods || [];
};

export const metadata = {
  title: "All Foods",
  description: "Generated by create next app",
};

const FoodsPage = async ({ searchParams }) => {
  const { search = "" } = await searchParams;
  const foods = await getFoods(search);

  return (
    <div>
      <h2 className={`text-4xl font-bold ${style.bgred}`}>
        Total {foods.length} Foods Found
      </h2>
      <div className="my-4">
        <InputSearch />
      </div>
      <div className="flex gap-5">
        <div className="flex-1 grid grid-cols-3 my-6 gap-5">
          {foods.map((food) => (
            <FoodCard key={food.id} food={food} />
          ))}
        </div>
        <div className="w-80 border-2 rounded-xl p-4">
          <h2 className="text-2xl font-bold">Cart Items</h2>
          <hr />
          <CartItems />
        </div>
      </div>
    </div>
  );
};

export default FoodsPage;
