import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CartProvider from "@/context/CartProvider";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ["400", "500", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "Next js core concepts",
    template: "%s | Next js core concepts",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header className="px-5 py-2 flex justify-between gap-5 bg-stone-800 items-center">
          <Link href={"/"}>
            <Image width={48} height={12} src="/globe.svg" alt="" />
          </Link>
          <div className="space-x-5">
            <Link prefetch={false} href={"/foods"} className="btn">
              Foods
            </Link>
            <Link href={"/reviews"} className="btn">
              Reviews
            </Link>
            <Link href={"/feedbacks"} className="btn">
              Feedbacks
            </Link>
          </div>
        </header>
        <main className="px-5 py-8">
          <CartProvider>{children}</CartProvider>
        </main>
      </body>
    </html>
  );
}
