import ReviewsPage from "./ReviewsPage";

export const metadata = {
  title: { absolute: "Satisfied Users" },
  description: "Generated by create next app",
};

const AllReviews = () => {
  return (
    <div>
      <ReviewsPage />
    </div>
  );
};

export default AllReviews;
